ccflags-y := -I$(src)/../include
#EXTRA_CFLAGS += -DDEBUG


obj-m += appflid.o

appflid-objs += nf_hook.o
appflid-objs += config.o
appflid-objs += core.o
appflid-objs += count.o
appflid-objs += regexp.o
appflid-objs += read_confile.o
appflid-objs += ndinfo.o
appflid-objs += wellkn_port.o
appflid-objs += aproto.o
appflid-objs += nl_kcmd.o
appflid-objs += nl_log.o
appflid-objs += kfile.o

